name: Publish Data

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PUSH_TOKEN }}

    - name: Get Image Files
      run: |
        pushd python
        wget -qO- https://github.com/PSAM-5020-2025S-A/5020-utils/releases/latest/download/clouds.tar.gz | tar xz
        wget -qO- https://github.com/PSAM-5020-2025S-A/5020-utils/releases/latest/download/flowers.tar.gz | tar xz
        wget -qO- https://github.com/PSAM-5020-2025S-A/5020-utils/releases/latest/download/metfaces.tar.gz | tar xz
        mv data/image/metfaces/256/* data/image/metfaces/
        rm -rf data/image/metfaces/256 data/image/metfaces/1024
        popd

    - name: Gen Datasets
      run: |
        pip install numpy Pillow pandas scikit-learn
        mkdir data
        pushd python
        python gen_pixel_counts.py
        python gen_penguin_data.py
        python gen_font_pca_data.py
        python gen_sils_pca_data.py
        mv *.json *.csv ../data/
        popd

    - name: Push ¡¡everything!! to gh-pages
      run: |
        GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        TAG_NAME=${{ github.ref_name }}-$(git log --format=%h -1)
        git checkout --orphan gh-pages
        git reset .
        touch .nojekyll
        git add -f data/ clustering/ correlations/ distributions/ pca/
        git add -f index.html CNAME .nojekyll
        git commit -m "release $TAG_NAME"
        git push -f origin gh-pages
